#!/bin/sh

SNAPLIST=$(mktemp)

teardown() {
 rm -f $SNAPLIST
}

trap teardown 0
trap "exit 2" 1 2 3 15

ec2dsnap > $SNAPLIST

IDS=$(cat $SNAPLIST | grep BackupID | awk '{print $5}' | sort -u)

for id in $IDS; do
  local snaps fistsnap bdate vols
  snapshots=$(cat $SNAPLIST | grep $id | awk '{print $3}')
  firstsnap=$(echo $snapshots |head -n 1 | awk '{print $1}')
  bdate=$(cat $SNAPLIST | grep $firstsnap | grep BackupDate | awk '{print $5,$6}')
  vols=""
  for snapshot in ${snapshots}; do
    vols="$vols $(cat $SNAPLIST | grep $snapshot | grep VolumeID | awk '{print $5}')"
  done
  echo "$bdate  $id  $vols"
done
