#!/bin/sh

OUR_PATH=$(dirname $0)

. $OUR_PATH/backup_functions
setup_snaplist

IDS=$(snapshots_list | grep BackupID | awk '{print $5}' | sort -u)

for id in $IDS; do
  local snaps fistsnap bdate vols
  snapshots=$(snapshots_by_id $id)
  firstsnap=$(echo $snapshots |head -n 1 | awk '{print $1}')
  bdate=$(snapshots_date $firstsnap)
  vols=""
  for snapshot in ${snapshots}; do
    vols="$vols $(snapshots_volume $snapshot)"
  done
  echo "$bdate  $id  $vols"
done
