#!/bin/sh

OUR_PATH=$(dirname $0)
LIBSHELL_PATH="$OUR_PATH/libshell"

#       libshell by Alexey Gladkov is used here
#       for more info see http://git.altlinux.org/gears/l/libshell.git
. "$LIBSHELL_PATH/shell-error"

[ -z "$1" ] && fatal "No backup ID specified"
id=$1

. $OUR_PATH/backup_functions
setup_snaplist

for snap in $(snapshots_by_id $id); do
  snapshots_list | grep $snap
done
