#!/bin/sh

OUR_PATH=$(dirname $0)
LIBSHELL_PATH="$OUR_PATH/libshell"

#	libshell by Alexey Gladkov is used here
#	for more info see http://git.altlinux.org/gears/l/libshell.git
. "$LIBSHELL_PATH/shell-getopt"
. "$LIBSHELL_PATH/shell-error"

show_usage() {
  cat <<EOF
	Usage: $PROG [options]
	  -d, --description=description		Description string to add to snapshots
	  -l, --volume-list=volumes_file	File with list of volumes to backup
						Default: ./volumes

	  -h, --help				Show this help
EOF
}

while getoptex "d: description: l: volume-list: h help" "$@"; do
  case "$OPTOPT" in
    d|description)  DESCRIPTION="$OPTARG" ;;
    l|volume-list)  VOLFILE="$OPTARG" ;;
    h|help)  show_usage; exit ;;
  esac
done


VOLFILE=${VOLFILE:-$OUR_PATH/volumes}
DESCRIPTION=${DESCRIPTION:-"Created by simple-ec2-backup"}

NOW=$(date +%s)
NOW_H=$(date --rfc-3339=seconds)

VOLUMES=$(cat "$OUR_PATH/$VOLFILE" | egrep -v '^[[:blank:]]*(#|$)' | sed 's, ,_,' 2> /dev/null)
[ -z "$VOLUMES" ] && fatal "No volumes to backup specified in $VOLFILE"

do_snapshot() {
  local volume
  local volid
  local snap
  local info

  volume=$(echo $1 | awk -F: '{ print $1}')
  volid=$(echo $1 | awk -F: '{ print $2}')
  info=$(echo $1 | awk -F: '{ print $3}')

  snap=$(ec2addsnap -d "$DESCRIPTION" "$volume" | awk '{print $2}')
  echo $snap
  ec2addtag --hide-tags $snap -t "BackupID=${NOW}" -t "BackupDate=${NOW_H}" -t "BackupInfo=$info" -t "VolumeID=$volid" > /dev/null
}

for volume in $VOLUMES; do
  do_snapshot $volume &
done

wait 
